file(READ "${SOURCE_DIR}/include/libmdf/mdf.h" source_header)
file(READ "${SOURCE_DIR}/include/libmdf/mdf.h.in" template_header)
string(REPLACE "@LIBMDF_VERSION@" "0.0.0" template_header "${template_header}")
foreach(part MAJOR MINOR PATCH)
  string(REPLACE "@LIBMDF_VERSION_${part}@" "0" template_header "${template_header}")
endforeach()
if(NOT source_header STREQUAL template_header)
  message(FATAL_ERROR "Public source header and installed-header template differ beyond version macros; synchronize declarations and documentation")
endif()
file(READ "${GENERATED_INCLUDE_DIR}/libmdf/mdf.h" generated_header)
string(REGEX REPLACE "#define LIBMDF_VERSION [^\n]*" "#define LIBMDF_VERSION \"0.0.0\"" generated_header "${generated_header}")
foreach(part MAJOR MINOR PATCH)
  string(REGEX REPLACE "#define LIBMDF_VERSION_${part} [^\n]*" "#define LIBMDF_VERSION_${part} 0" generated_header "${generated_header}")
endforeach()
if(NOT generated_header STREQUAL source_header)
  message(FATAL_ERROR "Generated installed header differs from the documented public source header beyond version macros")
endif()
