set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
find_program(LIBMDF_CC aarch64-linux-gnu-gcc)
if(NOT LIBMDF_CC)
  message(FATAL_ERROR "aarch64-linux-gnu-gcc not found; set PATH to the cross toolchain")
endif()
set(CMAKE_C_COMPILER "${LIBMDF_CC}")
