set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
find_program(LIBMDF_CC arm-linux-gnueabihf-gcc)
if(NOT LIBMDF_CC)
  find_program(LIBMDF_CC armhf-linux-gnu-gcc)
endif()
if(NOT LIBMDF_CC)
  message(FATAL_ERROR "arm-linux-gnueabihf-gcc or armhf-linux-gnu-gcc not found; set PATH to the cross toolchain")
endif()
set(CMAKE_C_COMPILER "${LIBMDF_CC}")
