#ifndef LIBMDF_INTERNAL_H
#define LIBMDF_INTERNAL_H

#include "libmdf/mdf.h"

typedef mdf mdf_renderer;

typedef struct mdf_theme_style {
    const char *name;
    const char *heading[6];
    const char *emphasis;
    const char *strong;
    const char *emphasis_strong;
    const char *code_inline;
    const char *code_block;
    const char *quote;
    const char *quote_text;
    const char *list_marker;
    const char *link_text;
    const char *link_url;
    const char *thematic_break;
    const char *table_header;
    const char *table_wire;
} mdf_theme_style;

typedef struct mdf_parser {
    mdf_status (*parse)(struct mdf_parser *self, mdf_source *source, mdf_renderer *renderer, mdf_sink *sink);
    const char *(*error)(const struct mdf_parser *self);
    void (*destroy)(struct mdf_parser *self);
    void *impl;
} mdf_parser;

typedef struct mdf_memory_block {
    struct mdf_memory_block *next;
    size_t cap;
} mdf_memory_block;

typedef struct mdf_memory {
    mdf_allocator backing;
    mdf_memory_options opts;
    mdf_memory_block *free_list;
    size_t retained_bytes;
} mdf_memory;

typedef struct mdf_impl {
    mdf_format format;
    mdf_options opts;
    const mdf_theme_style *theme;
    mdf_allocator user_allocator;
    mdf_memory memory;
    mdf_allocator allocator;
    char error[256];
    char emit_fixed[512];
    char *emit_buf;
    size_t emit_len;
    size_t emit_cap;
    size_t emit_max_cap;
    int emit_using_heap;
    int emit_fixed_mode;
    int emit_owns_buf;
    int emit_workspace_owned;
    int in_paragraph;
    int in_pre;
    int html_open;
    int html_body_emitted;
    int html_footer_needs_newline;
    void *html_state;
    int quote_open;
    int quote_wrap_active;
    int quote_depth;
    int quote_text_open;
    int quote_prefix_indent;
    int list_item_open;
    int list_blank_newline_emitted;
    int suppress_list_hardbreak_space;
    int suppress_list_marker_padding;
    int pending_list_marker;
    int pending_list_marker_quote_context;
    char pending_list_marker_text[64];
    size_t pending_list_marker_len;
    int heading_open;
    int heading_level;
    int heading_style_suspended;
    int heading_style_pending_prefix;
    int pending_breaks;
    int pending_quote_end;
    int pending_quote_reopen_prefix;
    int pending_quote_paragraph_separator;
    int pending_list_quote_blank_indent;
    int code_style_open;
    int ansi_col;
    int ansi_writing_left_margin;
    int ansi_pending_left_margin;
    int ansi_wrap_indent;
    int ansi_wrap_indent_in_quote;
    int ansi_pending_space;
    int ansi_pending_space_no_split;
    int ansi_pending_space_plain;
    int ansi_pending_style_reset;
    int ansi_pending_style_reset_after_word;
    const char *ansi_pending_attached_style;
    const char *ansi_pending_final_emph_style;
    int ansi_pending_final_emph_suffix;
    int ansi_pending_final_emph_word_suffix;
    size_t ansi_pending_final_emph_base_len;
    size_t ansi_pending_final_emph_base_cols;
    const char *ansi_active_inline_style;
    const char *ansi_pending_inline_style;
    int ansi_line_has_space;
    char ansi_prev_char;
    int ansi_punct_quote_pending;
    char *ansi_word;
    size_t ansi_word_len;
    size_t ansi_word_cols;
    size_t ansi_word_cap;
    int ansi_flushing_word;
    char *pre_code_buf;
    size_t pre_code_len;
    size_t pre_code_cap;
    int pre_code_prefix_state;
    int pre_code_leading_cols;
    char pre_code_marker[16];
    size_t pre_code_marker_len;
    int pre_code_wrap_indent;
    int table_cell_mode;
    int inline_mode;
    char *inline_text;
    size_t inline_text_len;
    size_t inline_text_cap;
    int inline_outer_paren_candidate;
    int inline_outer_paren_pending;
    char *inline_url;
    size_t inline_url_len;
    size_t inline_url_cap;
    char *pending_fallback_url;
    size_t pending_fallback_url_len;
    size_t pending_fallback_url_cap;
    int pending_fallback_exact;
    int pending_wrapped_link_fallback;
    int pending_wrapped_link_outer_paren;
    int pending_wrapped_link_outer_close;
    int pending_wrapped_link_punct_valid;
    char pending_wrapped_link_punct;
    char *inline_code;
    size_t inline_code_len;
    size_t inline_code_cap;
    size_t inline_code_delim_len;
    size_t inline_code_pending_ticks;
    char *ansi_pending_emit;
    size_t ansi_pending_emit_len;
    size_t ansi_pending_emit_cap;
    size_t *ansi_pending_emit_offsets;
    size_t ansi_pending_emit_offsets_len;
    size_t ansi_pending_emit_offsets_cap;
    int ansi_pending_emit_start_col;
    int ansi_pending_emit_valid;
    int ansi_pending_autolink_emit_valid;
    int ansi_pending_fallback_emit_valid;
    char *inline_emph;
    size_t inline_emph_len;
    size_t inline_emph_cap;
    char inline_emph_delim;
    int inline_emph_count;
    int inline_emph_close_count;
    int inline_emph_pending;
    int inline_emph_after_word;
    int inline_emph_streaming;
    int inline_emph_skip_spaces;
    char inline_emph_nested_delim;
    char *inline_entity;
    size_t inline_entity_len;
    size_t inline_entity_cap;
    int inline_html_nbsp_pending;
    int inline_html_nbsp_prev_digit;
} mdf_impl;

typedef struct mdf_parser_impl {
    mdf_options opts;
    mdf_allocator allocator;
    char error[256];
    int at_line_start;
    int in_code_block;
    int in_indent_code;
    size_t list_continuation_indent;
    size_t list_visual_continuation_indent;
    size_t list_source_indents[16];
    size_t list_visual_indents[16];
    size_t list_stack_len;
    size_t ordered_source_indent;
    unsigned long ordered_next;
    int ordered_active;
    int pending_list_item_end;
    int list_blank_pending;
    int pending_list_blank_breaks;
    int list_hard_break_pending;
    int pending_quoted_list_blank_depth;
    int pending_bare_quote_blank_depth;
    int prev_quote_depth;
    int prev_quote_line_text;
    int prev_hard_break;
    int pending_space;
    char marker[8];
    size_t marker_len;
} mdf_parser_impl;

typedef struct mdf_table_filter mdf_table_filter;

void mdf_allocator_normalize(mdf_allocator *allocator);
void mdf_memory_init(mdf_memory *memory, const mdf_allocator *backing, const mdf_memory_options *opts);
void mdf_memory_destroy(mdf_memory *memory);
mdf_allocator mdf_memory_allocator(mdf_memory *memory);
void *mdf_alloc(mdf_allocator *allocator, size_t size);
void *mdf_realloc_mem(mdf_allocator *allocator, void *ptr, size_t old_size, size_t new_size);
void mdf_free_mem(mdf_allocator *allocator, void *ptr, size_t size);
void mdf_renderer_reset_session_state(mdf_renderer *self);
void mdf_render_reset_state(mdf_impl *impl);
void mdf_render_release_state(mdf_impl *impl);
void mdf_set_error(mdf_renderer *self, const char *msg);
void mdf_parser_set_error(mdf_parser *self, const char *msg);
int mdf_write_all(mdf_sink *sink, const char *src, size_t len);
int mdf_write_cstr(mdf_sink *sink, const char *src);
int mdf_emit_all(mdf_impl *impl, mdf_sink *sink, const char *src, size_t len);
int mdf_emit_cstr(mdf_impl *impl, mdf_sink *sink, const char *src);
int mdf_emit_buffer_reset(mdf_impl *impl);
int mdf_emit_buffer_append(mdf_impl *impl, const char *src, size_t len);
int mdf_emit_buffer_append_cstr(mdf_impl *impl, const char *src);
int mdf_emit_buffer_commit(mdf_impl *impl, mdf_sink *sink);
mdf_status mdf_parser_create(const mdf_options *opts, mdf_parser **out);
const mdf_theme_style *mdf_theme_resolve(const char *name);
mdf_status mdf_parser_parse(mdf_parser *self, mdf_source *source, mdf_renderer *renderer, mdf_sink *sink);
const char *mdf_parser_error(const mdf_parser *self);
void mdf_parser_destroy(mdf_parser *self);
mdf_status mdf_renderer_write_token_internal(mdf_renderer *self, const mdf_token *token, mdf_sink *sink);
mdf_status mdf_renderer_finish_internal(mdf_renderer *self, mdf_sink *sink);
mdf_status mdf_renderer_begin_internal(mdf_renderer *self, mdf_sink *sink);
mdf_status mdf_parse_stream(mdf_parser *self, mdf_source *source, mdf_renderer *renderer, mdf_sink *sink);

#endif
